// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUfM5WEZUodXOAPSpdQlOEpqNy-o1NHqM',
    appId: '1:752590644718:web:fbf5fd7132c50a8ce8daff',
    messagingSenderId: '752590644718',
    projectId: 'user-management-7677b',
    authDomain: 'user-management-7677b.firebaseapp.com',
    storageBucket: 'user-management-7677b.appspot.com',
    measurementId: 'G-PH440R2Y10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdirhdLj51n6Nfz9yc8LU5an-vG2PNw18',
    appId: '1:752590644718:android:c12da19d3c8642a7e8daff',
    messagingSenderId: '752590644718',
    projectId: 'user-management-7677b',
    storageBucket: 'user-management-7677b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6qkl9QYBwqd11HH7HxVb8JwSpkwU6yA0',
    appId: '1:752590644718:ios:4a413f4eafacb997e8daff',
    messagingSenderId: '752590644718',
    projectId: 'user-management-7677b',
    storageBucket: 'user-management-7677b.appspot.com',
    iosBundleId: 'com.example.userManagementApp',
  );
}
